name: Auto Publish Website # 自动部署的名称
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行环境，告诉它运行在什么环境
    steps: # 步骤

    # 第一步：下载源码（CI/CD拉取代码到自己的本地）
    - name: Checkout
      uses: actions/checkout@main

    # 第二步：上传源码  
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "Blog/*"        # 上传tests下所有文件
        target: "/usr/src/hexo-upload"   # 上传在root/ 下
        

    # 第三步：部署到服务器
    - name: Deploy
      uses: appleboy/ssh-action@master # 使用ssh链接服务器
      with:
        host: ${{ secrets.HOST }} #配置的服务器地址
        username: ${{ secrets.USERNAME }} #配置的服务器用户名
        password: ${{ secrets.PASSWORD }} #配置的密码
        port: ${{ secrets.PORT }} #配置的端口
        script: | # 执行命令（运行到服务器）cd：要确保服务器有这个目录； wget：下载上一步的release到服务器； tar：解压； 安装依赖；启动服务
          cd /usr/src/hexo-upload
          docker rm -f kiaserblog
          docker rmi -f kiaserblog:latest
          docker build -t kiaserblog:latest .
          docker run --name kiaserblog -p 8082:80 -d kiaserblog:latest
